'use strict';

// tests for createCustomer
// Generated by serverless-mocha-plugin
process.env.SERVERLESS_TEST_ROOT = '';
const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('createCustomer', '/.esbuild/.build/src/functions/customer/handler.js', 'createCustomer');

describe('createCustomer', () => {
  before((done) => {
    done();
  });

  it('implement tests here', async () => {
    const response = await wrapped.run({
      "name": "Carlos David",
      "lastname": "Terrones España",
      "creditAvailable": 0
  });
    console.log('response', response);
    expect(response).to.not.be.empty;
  });
});
