'use strict';

// tests for getAllCustomer
// Generated by serverless-mocha-plugin

// Create default event
let event_get = {
  httpMethod: 'get',
  path: '/',
  body: {},
  headers: {
    'Content-Type': 'application/json'
  }
}

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('getAllCustomer', '/.esbuild/.build/src/functions/customer/handler.js', 'getAllCustomers');

describe('getAllCustomer', () => {
  before((done) => {
    done();
  });

  it('Prueba listar clientes', async () => {
    // Customize event
    let _event = Object.assign({},event_get,{
      body: '{}'
    })
    console.log('request', JSON.parse(_event.body))

    const response = await wrapped.run({});

    expect(response).to.not.be.empty;
    expect(response.statusCode).to.be.equal(200);

    const body = JSON.parse(response.body);
    console.log('response customers length', body.customers.length)
    
    expect(body).to.has.property('customers')
    expect(body).to.property('customers').to.be.an('array');
  });
});
