'use strict';

// tests for getAllCustomer
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('getAllCustomer', '/.esbuild/.build/src/functions/customer/handler.js', 'getAllCustomers');

describe('getAllCustomer', () => {
  before((done) => {
    done();
  });

  it('it should return all customers or void array instead', async () => {
    const response = await wrapped.run({});
    console.log('response: ', response)
    expect(response.statusCode).to.have.equal(200)
    expect(typeof response).to.be.equal('object');
    expect(JSON.parse(response.body)).to.have.property('customers');
    //expect(JSON.parse(response.body)).to.have.property('customers').with.lengthOf(1);
    //expect(typeof response).to.not.be.empty;
  });
});
